Script started on 2020-12-09 22:48:22-07:00
]0;ahmad.almasri3@csa2:~/cpsc355/xproahmad.almasri3@csa2:~/cpsc355/xpro$ ./script.sh 
]0;ahmad.almasri3@csa2:~/cpsc355/xproahmad.almasri3@csa2:~/cpsc355/xpro$ ./exAll Ahmad 20 20
negative numbers :: 0.400000 :: 160 ::
Reward numbers :: 0.200000 :: 80 ::


 -14.56  4.67  14.29  7.04  15.41  -10.75  -0.98  20.00  5.64  13.43  12.19  20.00  0.17  20.00  -15.98  -2.04  -9.98  6.96  14.61  11.03 
 15.78  4.93  -0.40  18.00  -1.97  2.13  -9.66  -6.52  -7.27  1.58  -13.29  20.00  -11.04  0.18  15.10  8.71  -5.63  -5.01  12.95  -0.59 
 14.03  -1.86  4.29  20.00  -11.71  -4.10  3.53  -1.43  4.31  -11.18  19.00  -5.64  -12.15  18.00  -2.22  -3.07  18.00  2.33  -0.17  -11.53 
 5.37  -11.71  5.21  0.25  18.00  -4.67  -6.38  -5.23  -6.09  19.00  20.00  -0.09  -10.97  6.42  11.44  2.18  19.00  19.00  -13.24  19.00 
 -14.55  -8.73  5.04  15.18  -13.73  -1.51  13.15  -12.13  0.28  -9.34  20.00  -2.82  -2.30  -9.03  7.94  5.47  9.39  -9.39  -11.34  4.57 
 12.15  -6.35  -2.86  11.39  -7.38  1.26  -12.04  -8.02  15.93  19.00  -5.58  -2.05  -13.99  17.00  -14.43  1.83  5.57  7.46  18.00  19.00 
 -7.62  -8.39  -1.37  20.00  -12.06  14.72  19.00  18.00  15.78  -14.02  0.30  1.72  -7.67  -4.66  -5.62  0.17  19.00  18.00  -5.94  3.48 
 14.21  -11.44  19.00  14.77  -15.30  -12.90  -6.31  3.46  10.04  -0.31  -0.02  1.01  -12.42  2.50  20.00  6.81  15.84  -3.40  18.00  6.78 
 -3.15  19.00  -0.36  -9.54  18.00  20.00  5.63  19.00  -0.81  -10.62  20.00  3.64  -11.76  5.47  0.59  10.53  -15.65  7.33  4.93  18.00 
 14.38  -11.08  18.00  18.00  2.07  20.00  5.20  -0.27  9.48  18.00  -0.29  20.00  11.02  -15.26  12.91  -6.80  -8.85  7.71  -4.84  14.78 
 1.75  -14.17  18.00  -12.55  19.00  15.79  8.35  -9.14  19.00  -12.82  -3.93  -12.71  2.25  14.74  -7.83  -15.46  20.00  19.00  1.07  4.82 
 11.96  8.54  0.38  -15.51  4.72  18.00  13.18  0.41  11.62  -4.96  -8.43  9.41  5.71  -6.73  -8.81  10.64  10.54  -0.30  -6.51  5.46 
 -8.71  2.09  0.22  18.00  -11.11  -14.53  18.00  -1.21  19.00  -8.89  19.00  0.82  20.00  -8.32  14.46  18.00  7.02  -4.62  19.00  18.00 
 -14.50  -12.77  18.00  -12.37  -11.89  15.92  -1.50  20.00  -15.58  -2.40  -9.52  13.02  20.00  3.45  18.00  -14.85  0.97  14.00  5.85  20.00 
 20.00  19.00  0.64  15.55  11.17  2.24  13.56  4.14  18.00  -1.94  -0.57  5.55  12.75  0.35  20.00  12.53  20.00  6.58  -12.50  -1.87 
 -7.86  -6.07  13.78  -12.61  -6.52  4.22  -4.78  7.86  9.43  -15.01  2.71  19.00  14.19  18.00  10.25  -3.60  8.46  -7.75  4.47  -11.60 
 13.39  18.00  7.36  1.06  7.30  -5.48  -8.70  -15.72  15.12  -5.28  19.00  14.17  -15.41  3.36  5.81  13.82  15.13  0.30  -6.84  10.01 
 20.00  -0.39  3.85  19.00  -2.10  5.25  19.00  20.00  -14.97  13.24  -4.74  20.00  -10.13  12.83  18.00  18.00  -13.89  -7.17  -14.35  -15.54 
 -1.06  -5.46  -10.16  -15.67  -8.47  -10.31  18.00  1.03  6.75  -6.55  13.09  8.57  -6.82  -11.01  12.84  13.51  1.61  10.63  -2.66  8.31 
 20.00  10.56  10.75  4.67  -3.64  -15.97  19.00  19.00  -10.06  10.59  8.83  5.14  6.04  5.82  -1.68  4.18  19.00  13.35  -9.41  20.00 


Do you want to display top scores?( 0 / 1 )
0



 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 3
Score : 0.00
Bombs : 20

Enter the (x , y) OR (50 , 50) to exit:
5 5




:: UPDATE :: The current uncovered score ::  -17.60  ::
:: Note :: Score <= 0 :: 1 life is lost ::
:: UPDATE :: Lives (+/-) value ::  -1  ::
:: UPDATE :: Bombs (+/-) value ::  -3  ::

 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  -  +  -  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  -  +  @  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 2
Score : 0.00
Bombs : 17

Enter the (x , y) OR (50 , 50) to exit:
10 10




:: UPDATE :: The current uncovered score ::  -33.73  ::
:: Note :: Score <= 0 :: 1 life is lost ::
:: UPDATE :: Lives (+/-) value ::  0  ::
:: UPDATE :: Bombs (+/-) value ::  -1  ::
:: UPDATE :: Value Of Gained Double Range ::  2  ::

 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  -  +  -  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  -  +  @  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  $  -  #  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  -  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  +  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 2
Score : 0.00
Bombs : 16

Enter the (x , y) OR (50 , 50) to exit:
40 40
The numbers are out of range .... 


Enter the (x , y) OR (50 , 50) to exit:
5 10




:: UPDATE :: The current uncovered score ::  -42.62  ::
:: Note :: Score <= 0 :: 1 life is lost ::
:: UPDATE :: Lives (+/-) value ::  1  ::
:: UPDATE :: Bombs (+/-) value ::  -3  ::

 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  -  @  #  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  +  -  #  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  +  -  X  +  @  -  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  +  @  X  +  -  +  +  -  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  +  -  -  +  -  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  $  -  #  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  -  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  +  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 3
Score : 0.00
Bombs : 13

Enter the (x , y) OR (50 , 50) to exit:
5 15




:: UPDATE :: The current uncovered score ::  10.33  ::
:: UPDATE :: Lives (+/-) value ::  0  ::
:: UPDATE :: Bombs (+/-) value ::  -3  ::

 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  -  @  #  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  +  -  #  -  -  X  +  +  +  X  X  X 
 X  X  X  X  -  +  -  X  +  @  -  -  -  X  -  +  +  X  X  X 
 X  X  X  X  -  +  @  X  +  -  +  +  -  X  -  +  @  X  X  X 
 X  X  X  X  X  X  X  X  +  -  -  +  -  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  $  -  #  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  -  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  +  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 3
Score : 10.33
Bombs : 10

Enter the (x , y) OR (50 , 50) to exit:
1 1




:: UPDATE :: The current uncovered score ::  41.17  ::
:: UPDATE :: Lives (+/-) value ::  0  ::
:: UPDATE :: Bombs (+/-) value ::  -1  ::

 -  +  +  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 +  +  -  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 +  -  +  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  -  @  #  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  +  -  #  -  -  X  +  +  +  X  X  X 
 X  X  X  X  -  +  -  X  +  @  -  -  -  X  -  +  +  X  X  X 
 X  X  X  X  -  +  @  X  +  -  +  +  -  X  -  +  @  X  X  X 
 X  X  X  X  X  X  X  X  +  -  -  +  -  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  $  -  #  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  -  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  -  -  +  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 3
Score : 51.50
Bombs : 9

Enter the (x , y) OR (50 , 50) to exit:
10 2




:: UPDATE :: The current uncovered score ::  -44.40  ::
:: UPDATE :: Lives (+/-) value ::  0  ::
:: UPDATE :: Bombs (+/-) value ::  -1  ::
:: UPDATE :: Value Of Gained Double Range ::  8  ::

 -  +  +  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 +  +  -  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 +  -  +  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  -  @  #  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  +  -  #  -  -  X  +  +  +  X  X  X 
 X  X  X  X  -  +  -  X  +  @  -  -  -  X  -  +  +  X  X  X 
 X  X  X  X  -  +  @  X  +  -  +  +  -  X  -  +  @  X  X  X 
 X  X  X  X  X  X  X  X  +  -  -  +  -  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  -  $  $  X  X  X  X  X  $  -  #  X  X  X  X  X  X  X  X 
 X  -  $  -  X  X  X  X  X  -  -  -  X  X  X  X  X  X  X  X 
 X  +  +  -  X  X  X  X  X  -  -  +  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 

Lives : 3
Score : 7.11
Bombs : 8

Enter the (x , y) OR (50 , 50) to exit:
15 10




:: UPDATE :: The current uncovered score ::  124.37  ::
:: UPDATE :: Lives (+/-) value ::  4  ::
:: UPDATE :: Bombs (+/-) value ::  -16  ::
:: UPDATE :: Value Of Gained Double Range ::  8192  ::

:: UPDATE :: You lost ::::  Bombs (@) <= 0

 -  +  +  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 +  +  -  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 +  -  +  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X  X 
 X  X  X  X  X  X  X  X  -  @  #  -  -  X  X  X  X  X  X  X 
 X  X  X  X  -  -  +  X  +  -  #  -  -  X  +  +  +  X  X  X 
 X  X  X  X  -  +  -  X  +  @  -  -  -  X  -  +  +  X  X  X 
 X  X  X  X  -  +  @  X  +  -  +  +  -  X  -  +  @  X  X  X 
 X  X  @  +  -  -  -  +  +  -  -  +  -  +  #  +  +  -  $  X 
 X  X  -  -  $  #  +  @  -  -  #  +  -  +  +  +  -  +  +  X 
 X  -  $  $  +  #  +  -  +  $  -  #  +  -  +  -  -  +  -  X 
 X  -  $  -  @  +  +  -  @  -  -  -  +  +  -  -  #  @  +  X 
 X  +  +  -  +  $  +  +  +  -  -  +  +  -  -  +  +  -  -  X 
 X  X  +  $  -  -  $  -  @  -  @  +  #  -  +  $  +  -  @  X 
 X  X  $  -  -  +  -  #  -  -  -  +  #  +  $  -  +  +  +  X 
 X  X  +  +  +  +  +  +  $  -  -  +  +  +  #  +  #  +  -  X 
 X  X  +  -  -  +  -  +  +  -  +  @  +  $  +  -  +  -  +  X 
 X  X  +  +  +  -  -  -  +  -  @  +  -  +  +  +  +  +  -  X 
 X  X  +  @  -  +  @  #  -  +  -  #  -  +  $  $  -  -  -  X 
 X  X  -  -  -  -  $  +  +  -  +  +  -  -  +  +  +  +  -  X 
 X  X  +  +  -  -  @  @  -  +  +  +  +  +  -  +  @  +  -  X 

Lives : 7
Score : 131.47
Bombs : -8





Do you want to display top scores?( 0 / 1 )
1
:::: Enter number of scores ::::
2
Ahmad	131.47		55.00	
Omar	90.26		67.00	
]0;ahmad.almasri3@csa2:~/cpsc355/xproahmad.almasri3@csa2:~/cpsc355/xpro$ exit
exit

Script done on 2020-12-09 22:49:59-07:00
